use minijinja::Environment;
use serde::Serialize;

#[derive(Serialize)]
pub struct BuildScriptContext {
    pub build_platform: BuildPlatform,
    pub source_dir: String,
    pub extra_args: Vec<String>,
    /// Directory the build tree is configured in, relative to the work
    /// directory the script runs in.
    pub build_dir: &'static str,
    /// Contents of the CMake toolchain file that pins the compilers.
    /// Empty when none of the compilers map to a CMake language.
    pub toolchain_file_lines: Vec<String>,
    /// Contents of the CMake file that registers the dependency provider.
    pub provider_file_lines: Vec<String>,
    /// Directory the discovery run builds in.
    pub discovery_dir: &'static str,
    /// Name of the record the discovery run leaves in that directory.
    pub find_log_name: &'static str,
    /// Client name of the CMake file API query the build script leaves behind.
    pub file_api_client: &'static str,
    /// The CMake file API query itself.
    pub file_api_query: &'static str,
}

/// The CMake compiler variable and the environment variable that the conda
/// compiler activation scripts export for a compiler.
fn toolchain_compiler(compiler: &str) -> Option<(&'static str, &'static str)> {
    match compiler {
        "c" => Some(("CMAKE_C_COMPILER", "CC")),
        "cxx" => Some(("CMAKE_CXX_COMPILER", "CXX")),
        "fortran" => Some(("CMAKE_Fortran_COMPILER", "FC")),
        "cuda" => Some(("CMAKE_CUDA_COMPILER", "CUDACXX")),
        _ => None,
    }
}

/// Renders the CMake toolchain file that pins each compiler to the one
/// activated in the build environment.
///
/// Every entry is guarded on the environment variable being set, so a compiler
/// that is missing from the build environment keeps CMake's own detection.
pub fn toolchain_file_lines(compilers: &[String]) -> Vec<String> {
    let entries: Vec<_> = compilers
        .iter()
        .filter_map(|compiler| toolchain_compiler(compiler))
        .collect();

    if entries.is_empty() {
        return Vec::new();
    }

    std::iter::once(
        "# Generated by pixi-build-cmake: the compilers of the build environment.".to_string(),
    )
    .chain(
        entries
            .into_iter()
            .flat_map(|(cmake_variable, env_variable)| {
                [
                    format!("if(NOT \"$ENV{{{env_variable}}}\" STREQUAL \"\")"),
                    format!("set({cmake_variable} \"$ENV{{{env_variable}}}\")"),
                    "endif()".to_string(),
                ]
            }),
    )
    .collect()
}

#[derive(Copy, Clone, Serialize)]
#[serde(rename_all = "kebab-case")]
#[cfg_attr(test, derive(strum::Display))]
#[cfg_attr(test, strum(serialize_all = "snake_case"))]
pub enum BuildPlatform {
    Windows,
    Unix,
}

impl BuildScriptContext {
    pub fn render(&self) -> String {
        let env = Environment::new();
        let template = env
            .template_from_str(include_str!("build_script.j2"))
            .unwrap();
        template.render(self).unwrap().trim().to_string()
    }
}

#[cfg(test)]
mod test {
    use rstest::*;

    use super::*;
    use crate::{discovery, file_api, inputs};

    /// A context for a project built from `source_dir` with `compilers`,
    /// carrying the discovery and file API settings the backend always passes.
    fn context(
        build_platform: BuildPlatform,
        source_dir: &str,
        extra_args: Vec<String>,
        compilers: &[String],
    ) -> BuildScriptContext {
        BuildScriptContext {
            build_platform,
            source_dir: String::from(source_dir),
            extra_args,
            build_dir: inputs::NINJA_BUILD_DIR,
            toolchain_file_lines: toolchain_file_lines(compilers),
            provider_file_lines: discovery::provider_file_lines(),
            discovery_dir: discovery::DISCOVERY_DIR,
            find_log_name: discovery::FIND_LOG,
            file_api_client: file_api::CLIENT,
            file_api_query: file_api::QUERY,
        }
    }

    #[rstest]
    fn test_build_script(
        #[values(BuildPlatform::Windows, BuildPlatform::Unix)] build_platform: BuildPlatform,
        #[values(vec![String::from("test-arg")], vec![])] extra_args: Vec<String>,
    ) {
        let script = context(
            build_platform,
            "my-prefix-dir",
            extra_args.clone(),
            &[String::from("cxx")],
        )
        .render();

        let mut settings = insta::Settings::clone_current();
        settings.set_snapshot_suffix(format!(
            "{}-{}",
            build_platform,
            if extra_args.is_empty() {
                "no-extra-args"
            } else {
                "with-extra-args"
            }
        ));
        settings.bind(|| {
            insta::assert_snapshot!(script);
        });
    }

    #[rstest]
    fn test_build_script_multiple_compilers(
        #[values(BuildPlatform::Windows, BuildPlatform::Unix)] build_platform: BuildPlatform,
    ) {
        let compilers = ["c", "cxx", "fortran", "cuda"].map(String::from);
        let script = context(build_platform, "my-prefix-dir", vec![], &compilers).render();

        let mut settings = insta::Settings::clone_current();
        settings.set_snapshot_suffix(build_platform.to_string());
        settings.bind(|| {
            insta::assert_snapshot!(script);
        });
    }

    /// A project that needs no compiler gets no toolchain file, and the
    /// configure step is left untouched.
    #[rstest]
    fn test_build_script_without_compilers(
        #[values(BuildPlatform::Windows, BuildPlatform::Unix)] build_platform: BuildPlatform,
    ) {
        let script = context(build_platform, "my-prefix-dir", vec![], &[]).render();

        assert!(!script.contains("conda-toolchain.cmake"));
    }

    #[test]
    fn test_toolchain_file_is_empty_for_unmapped_compilers() {
        assert!(toolchain_file_lines(&[]).is_empty());
        assert!(toolchain_file_lines(&[String::from("rust")]).is_empty());
    }

    #[test]
    fn test_toolchain_file_guards_every_compiler() {
        let lines = toolchain_file_lines(&[String::from("c"), String::from("cxx")]);

        insta::assert_snapshot!(lines.join("\n"));
    }

    /// Renders the script for a platform, with a toolchain file and the file
    /// API query.
    fn render(build_platform: BuildPlatform) -> String {
        context(build_platform, "/src/demo", vec![], &[String::from("cxx")]).render()
    }

    /// An install prefix holding a space must reach cmake as one argument, so
    /// the value has to be quoted in the script.
    #[test]
    fn test_the_install_prefix_is_quoted() {
        assert!(
            render(BuildPlatform::Unix).contains(r#"-DCMAKE_INSTALL_PREFIX="$PREFIX""#),
            "the unix install prefix is unquoted"
        );
        assert!(
            render(BuildPlatform::Windows).contains(r#"-DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%""#),
            "the windows install prefix is unquoted"
        );
    }

    /// Runs a rendered script with stubs on PATH instead of a real toolchain,
    /// and returns the arguments of every configure call it made.
    ///
    /// This is what proves the quoting works rather than merely being present:
    /// the shell, not a string comparison, decides where the arguments split.
    #[cfg(unix)]
    fn configure_invocations(prefix: &str, python: Option<&str>) -> Vec<Vec<String>> {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().expect("failed to create a temp dir");
        let record = dir.path().join("argv");

        let write_stub = |name: &str, body: &str| {
            let path = dir.path().join(name);
            fs_err::write(&path, body).expect("failed to write a stub");
            let mut permissions = fs_err::metadata(&path).unwrap().permissions();
            permissions.set_mode(0o755);
            fs_err::set_permissions(&path, permissions).expect("failed to chmod a stub");
        };
        write_stub(
            "cmake",
            "#!/bin/sh\n{ echo '--- invocation'; for arg in \"$@\"; do echo \"$arg\"; done; } >> \"$ARGV_RECORD\"\nexit 0\n",
        );
        write_stub("ninja", "#!/bin/sh\nexit 0\n");

        let script = dir.path().join("build.sh");
        fs_err::write(&script, render(BuildPlatform::Unix)).expect("failed to write the script");

        let output = std::process::Command::new("bash")
            .arg(&script)
            .current_dir(dir.path())
            .env("ARGV_RECORD", &record)
            .env("PATH", format!("{}:/usr/bin:/bin", dir.path().display()))
            .env("PREFIX", prefix)
            .env("CMAKE_ARGS", "")
            .env(
                "PYTHON",
                python.map_or_else(
                    || {
                        dir.path()
                            .join("no-such-python")
                            .to_string_lossy()
                            .into_owned()
                    },
                    str::to_string,
                ),
            )
            .output()
            .expect("failed to run the script");
        assert!(
            output.status.success(),
            "the script failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );

        // Configure calls are the invocations that name a source directory.
        // The discovery run comes first, the real configure after it.
        let recorded = fs_err::read_to_string(&record).expect("the stub recorded nothing");
        recorded
            .split("--- invocation\n")
            .map(|invocation| {
                invocation
                    .lines()
                    .map(str::to_string)
                    .collect::<Vec<String>>()
            })
            .filter(|arguments| arguments.iter().any(|argument| argument == "-S"))
            .collect()
    }

    /// The arguments of the real configure run, which follows the discovery.
    #[cfg(unix)]
    fn configure_arguments(prefix: &str, python: Option<&str>) -> Vec<String> {
        configure_invocations(prefix, python)
            .pop()
            .expect("no configure invocation was recorded")
    }

    #[cfg(unix)]
    #[test]
    fn test_configure_gets_a_spaced_prefix_as_one_argument() {
        let arguments = configure_arguments("/tmp/a prefix with spaces", None);

        assert!(
            arguments.contains(&"-DCMAKE_INSTALL_PREFIX=/tmp/a prefix with spaces".to_string()),
            "the prefix was split up: {arguments:?}"
        );
    }

    /// The interpreter flag must not go through CMAKE_ARGS, which the
    /// configure step expands unquoted and would split on the space.
    #[test]
    fn test_the_python_flag_bypasses_cmake_args() {
        for platform in [BuildPlatform::Unix, BuildPlatform::Windows] {
            let script = render(platform);
            assert!(
                !script.contains("CMAKE_ARGS% -DPython_EXECUTABLE")
                    && !script.contains("CMAKE_ARGS -DPython_EXECUTABLE"),
                "the interpreter is appended to CMAKE_ARGS on {platform}"
            );
            assert!(
                script.contains("PYTHON_ARG"),
                "the interpreter flag has no variable of its own on {platform}"
            );
        }
    }

    #[cfg(unix)]
    #[test]
    fn test_configure_gets_a_spaced_interpreter_as_one_argument() {
        use std::os::unix::fs::PermissionsExt;

        // The probe only passes the flag on for an executable file.
        let home = tempfile::tempdir().expect("failed to create a temp dir");
        let python = home.path().join("a dir with spaces").join("python");
        fs_err::create_dir_all(python.parent().unwrap()).unwrap();
        fs_err::write(&python, "#!/bin/sh\nexit 0\n").unwrap();
        let mut permissions = fs_err::metadata(&python).unwrap().permissions();
        permissions.set_mode(0o755);
        fs_err::set_permissions(&python, permissions).unwrap();

        let arguments = configure_arguments("/tmp/prefix", Some(&python.to_string_lossy()));

        assert!(
            arguments.contains(&format!("-DPython_EXECUTABLE={}", python.display())),
            "the interpreter path was split up: {arguments:?}"
        );
    }

    /// Without an interpreter the flag must vanish rather than arrive empty,
    /// which would make cmake complain about an unparsable definition.
    #[cfg(unix)]
    #[test]
    fn test_configure_gets_no_python_flag_without_an_interpreter() {
        let arguments = configure_arguments("/tmp/prefix", None);

        assert!(
            !arguments
                .iter()
                .any(|argument| argument.contains("Python_EXECUTABLE")),
            "an interpreter flag was passed anyway: {arguments:?}"
        );
        assert!(
            !arguments.iter().any(|argument| argument.is_empty()),
            "an empty argument reached cmake: {arguments:?}"
        );
    }

    /// The discovery run has to come first, in its own build tree, with the
    /// provider registered. The real configure must follow it without one.
    #[cfg(unix)]
    #[test]
    fn test_the_discovery_run_precedes_the_real_configure() {
        let invocations = configure_invocations("/tmp/prefix", None);

        assert_eq!(invocations.len(), 2, "expected a discovery and a real run");
        let [discovery, real] = &invocations[..] else {
            unreachable!("just asserted the length")
        };

        assert!(
            discovery
                .iter()
                .any(|argument| argument.starts_with("-DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=")),
            "the discovery run does not register the provider: {discovery:?}"
        );
        assert!(
            discovery
                .iter()
                .any(|argument| argument == discovery::DISCOVERY_DIR),
            "the discovery run shares the real build directory: {discovery:?}"
        );
        assert!(
            !real
                .iter()
                .any(|argument| argument.contains("CMAKE_PROJECT_TOP_LEVEL_INCLUDES")),
            "the real configure must not inherit the provider: {real:?}"
        );
        assert!(
            real.contains(&"-DCMAKE_BUILD_TYPE=Release".to_string()),
            "the real configure lost its arguments: {real:?}"
        );
    }

    /// The provider has to record what was asked for and whether it was found,
    /// and stand in for what is missing so one run sees every package.
    /// Discovery is for the first configure only; a rebuild must not pay for
    /// it again.
    #[test]
    fn test_the_discovery_run_is_skipped_once_the_build_tree_exists() {
        for platform in [BuildPlatform::Unix, BuildPlatform::Windows] {
            let script = render(platform);
            let discovery = script
                .find(discovery::DISCOVERY_DIR)
                .expect("a discovery run");
            let guard = script
                .find("build.ninja")
                .expect("a guard on the build tree");

            assert!(
                guard < discovery,
                "the discovery run is not guarded by the build tree on {platform}"
            );
        }
    }
}
