use minijinja::Environment;
use serde::Serialize;

#[derive(Serialize)]
pub struct BuildScriptContext {
    pub build_platform: BuildPlatform,
    pub source_dir: String,
    /// Extra configure arguments, already quoted for the shell that will run
    /// the script. Build one with [`quote_arguments`].
    pub extra_args: Vec<String>,
    /// Directory the build tree is configured in, relative to the work
    /// directory the script runs in.
    pub build_dir: &'static str,
    /// Contents of the CMake toolchain file that pins the compilers.
    /// Empty when none of the compilers map to a CMake language.
    pub toolchain_file_lines: Vec<String>,
    /// Contents of the CMake file that registers the dependency provider.
    pub provider_file_lines: Vec<String>,
    /// Directory the discovery run builds in.
    pub discovery_dir: &'static str,
    /// Name of the record the discovery run leaves in that directory.
    pub find_log_name: &'static str,
    /// Client name of the CMake file API query the build script leaves behind.
    pub file_api_client: &'static str,
    /// The CMake file API query itself.
    pub file_api_query: &'static str,
}

/// Quotes each configure argument so the shell passes it on as the single
/// argument it was written as.
///
/// The quotes are the kind that still expand variables, because an argument
/// naming `$PREFIX` or `%LIBRARY_PREFIX%` is the reason to write one by hand.
pub fn quote_arguments(arguments: &[String], build_platform: BuildPlatform) -> Vec<String> {
    arguments
        .iter()
        .map(|argument| match build_platform {
            // A backslash escapes in a double quoted word, so a Windows path
            // written for the other platform has to survive it.
            BuildPlatform::Unix => {
                format!(
                    "\"{}\"",
                    argument.replace('\\', "\\\\").replace('"', "\\\"")
                )
            }
            // cmd.exe has no escape character; a literal quote is written by
            // doubling it, and backslashes are just path separators.
            BuildPlatform::Windows => format!("\"{}\"", argument.replace('"', "\"\"")),
        })
        .collect()
}

/// The CMake compiler variable and the environment variable that the conda
/// compiler activation scripts export for a compiler.
fn toolchain_compiler(compiler: &str) -> Option<(&'static str, &'static str)> {
    match compiler {
        "c" => Some(("CMAKE_C_COMPILER", "CC")),
        "cxx" => Some(("CMAKE_CXX_COMPILER", "CXX")),
        "fortran" => Some(("CMAKE_Fortran_COMPILER", "FC")),
        "cuda" => Some(("CMAKE_CUDA_COMPILER", "CUDACXX")),
        _ => None,
    }
}

/// Renders the CMake toolchain file that pins each compiler to the one
/// activated in the build environment.
///
/// Every entry is guarded on the environment variable being set, so a compiler
/// that is missing from the build environment keeps CMake's own detection.
pub fn toolchain_file_lines(compilers: &[String]) -> Vec<String> {
    let entries: Vec<_> = compilers
        .iter()
        .filter_map(|compiler| toolchain_compiler(compiler))
        .collect();

    if entries.is_empty() {
        return Vec::new();
    }

    std::iter::once(
        "# Generated by pixi-build-cmake: the compilers of the build environment.".to_string(),
    )
    .chain(
        entries
            .into_iter()
            .flat_map(|(cmake_variable, env_variable)| {
                [
                    format!("if(NOT \"$ENV{{{env_variable}}}\" STREQUAL \"\")"),
                    format!("set({cmake_variable} \"$ENV{{{env_variable}}}\")"),
                    "endif()".to_string(),
                ]
            }),
    )
    .collect()
}

#[derive(Copy, Clone, Serialize)]
#[serde(rename_all = "kebab-case")]
#[cfg_attr(test, derive(strum::Display))]
#[cfg_attr(test, strum(serialize_all = "snake_case"))]
pub enum BuildPlatform {
    Windows,
    Unix,
}

impl BuildScriptContext {
    pub fn render(&self) -> String {
        let env = Environment::new();
        let template = env
            .template_from_str(include_str!("build_script.j2"))
            .unwrap();
        template.render(self).unwrap().trim().to_string()
    }
}

#[cfg(test)]
mod test {
    use rstest::*;

    use std::{path::Path, process::Command};

    use super::*;
    use crate::{discovery, file_api, inputs};

    /// A context for a project built from `source_dir` with `compilers`,
    /// carrying the discovery and file API settings the backend always passes.
    fn context(
        build_platform: BuildPlatform,
        source_dir: &str,
        extra_args: Vec<String>,
        compilers: &[String],
    ) -> BuildScriptContext {
        BuildScriptContext {
            build_platform,
            source_dir: String::from(source_dir),
            build_dir: inputs::NINJA_BUILD_DIR,
            extra_args: quote_arguments(&extra_args, build_platform),
            toolchain_file_lines: toolchain_file_lines(compilers),
            provider_file_lines: discovery::provider_file_lines(),
            discovery_dir: discovery::DISCOVERY_DIR,
            find_log_name: discovery::FIND_LOG,
            file_api_client: file_api::CLIENT,
            file_api_query: file_api::QUERY,
        }
    }

    #[rstest]
    fn test_build_script(
        #[values(BuildPlatform::Windows, BuildPlatform::Unix)] build_platform: BuildPlatform,
        #[values(vec![String::from("test-arg")], vec![])] extra_args: Vec<String>,
    ) {
        let script = context(
            build_platform,
            "my-prefix-dir",
            extra_args.clone(),
            &[String::from("cxx")],
        )
        .render();

        let mut settings = insta::Settings::clone_current();
        settings.set_snapshot_suffix(format!(
            "{}-{}",
            build_platform,
            if extra_args.is_empty() {
                "no-extra-args"
            } else {
                "with-extra-args"
            }
        ));
        settings.bind(|| {
            insta::assert_snapshot!(script);
        });
    }

    #[rstest]
    fn test_build_script_multiple_compilers(
        #[values(BuildPlatform::Windows, BuildPlatform::Unix)] build_platform: BuildPlatform,
    ) {
        let compilers = ["c", "cxx", "fortran", "cuda"].map(String::from);
        let script = context(build_platform, "my-prefix-dir", vec![], &compilers).render();

        let mut settings = insta::Settings::clone_current();
        settings.set_snapshot_suffix(build_platform.to_string());
        settings.bind(|| {
            insta::assert_snapshot!(script);
        });
    }

    /// A project that needs no compiler gets no toolchain file, and the
    /// configure step is left untouched.
    #[rstest]
    fn test_build_script_without_compilers(
        #[values(BuildPlatform::Windows, BuildPlatform::Unix)] build_platform: BuildPlatform,
    ) {
        let script = context(build_platform, "my-prefix-dir", vec![], &[]).render();

        assert!(!script.contains("conda-toolchain.cmake"));
    }

    /// A value holding a space has to reach cmake whole, and one naming a
    /// variable has to keep expanding.
    #[test]
    fn test_arguments_are_quoted_for_their_shell() {
        let arguments = [
            String::from("-DPLAIN=one"),
            String::from("-DSPACED=two words"),
            String::from("-DVAR=$PREFIX/lib"),
            String::from(r#"-DQUOTED=a "b" c"#),
        ];

        assert_eq!(
            quote_arguments(&arguments, BuildPlatform::Unix),
            [
                r#""-DPLAIN=one""#,
                r#""-DSPACED=two words""#,
                r#""-DVAR=$PREFIX/lib""#,
                r#""-DQUOTED=a \"b\" c""#,
            ]
        );
        assert_eq!(
            quote_arguments(&arguments, BuildPlatform::Windows),
            [
                r#""-DPLAIN=one""#,
                r#""-DSPACED=two words""#,
                r#""-DVAR=$PREFIX/lib""#,
                r#""-DQUOTED=a ""b"" c""#,
            ]
        );
    }

    /// A Windows path written into extra-args must not lose its separators to
    /// the escaping on the unix side.
    #[test]
    fn test_a_backslash_survives_unix_quoting() {
        let arguments = [String::from(r"-DDIR=C:\proj\include")];

        assert_eq!(
            quote_arguments(&arguments, BuildPlatform::Unix),
            [r#""-DDIR=C:\\proj\\include""#]
        );
        assert_eq!(
            quote_arguments(&arguments, BuildPlatform::Windows),
            [r#""-DDIR=C:\proj\include""#]
        );
    }

    #[test]
    fn test_toolchain_file_is_empty_for_unmapped_compilers() {
        assert!(toolchain_file_lines(&[]).is_empty());
        assert!(toolchain_file_lines(&[String::from("rust")]).is_empty());
    }

    #[test]
    fn test_toolchain_file_guards_every_compiler() {
        let lines = toolchain_file_lines(&[String::from("c"), String::from("cxx")]);

        insta::assert_snapshot!(lines.join("\n"));
    }

    /// Renders the script for a platform, with a toolchain file and the file
    /// API query.
    fn render(build_platform: BuildPlatform) -> String {
        render_with(build_platform, vec![])
    }

    /// As [`render`], with configure arguments from the manifest.
    fn render_with(build_platform: BuildPlatform, extra_args: Vec<String>) -> String {
        context(
            build_platform,
            "/src/demo",
            extra_args,
            &[String::from("cxx")],
        )
        .render()
    }

    /// An install prefix holding a space must reach cmake as one argument, so
    /// the value has to be quoted in the script.
    #[test]
    fn test_the_install_prefix_is_quoted() {
        assert!(
            render(BuildPlatform::Unix).contains(r#"-DCMAKE_INSTALL_PREFIX="$PREFIX""#),
            "the unix install prefix is unquoted"
        );
        assert!(
            render(BuildPlatform::Windows).contains(r#"-DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%""#),
            "the windows install prefix is unquoted"
        );
    }

    /// A cmake that records its arguments and leaves behind the `build.ninja`
    /// a real configure with the ninja generator would.
    #[cfg(unix)]
    const CMAKE_NINJA: &str = "#!/bin/sh\n{ echo '--- invocation'; for arg in \"$@\"; do echo \"$arg\"; done; } >> \"$ARGV_RECORD\"\n: > build.ninja\nexit 0\n";

    /// A cmake configuring some other generator, which extra-args can still
    /// ask for. It leaves no `build.ninja` behind, and records nothing, as
    /// only its exit status is of interest.
    #[cfg(unix)]
    const CMAKE_OTHER_GENERATOR: &str = "#!/bin/sh\nexit 0\n";

    /// A ninja that answers every query, as one does for a project whose
    /// CMakeLists.txt installs something.
    #[cfg(unix)]
    const NINJA_WITH_INSTALL: &str = "#!/bin/sh\nexit 0\n";

    /// A ninja that knows no `install` target, which is what CMake generates
    /// for a project that installs nothing.
    #[cfg(unix)]
    const NINJA_WITHOUT_INSTALL: &str =
        "#!/bin/sh\ncase \"$*\" in *'-t query install'*) exit 1 ;; esac\nexit 0\n";

    /// Runs a rendered script with stubs on PATH instead of a real toolchain,
    /// and returns what the script did: its output and every cmake call.
    ///
    /// This is what proves the quoting works rather than merely being present:
    /// the shell, not a string comparison, decides where the arguments split.
    #[cfg(unix)]
    fn run_script(
        cmake: &str,
        ninja: &str,
        extra_args: Vec<String>,
        prefix: &str,
        python: Option<&str>,
    ) -> (std::process::Output, Vec<Vec<String>>) {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().expect("failed to create a temp dir");
        let record = dir.path().join("argv");

        let write_stub = |name: &str, body: &str| {
            let path = dir.path().join(name);
            fs_err::write(&path, body).expect("failed to write a stub");
            let mut permissions = fs_err::metadata(&path).unwrap().permissions();
            permissions.set_mode(0o755);
            fs_err::set_permissions(&path, permissions).expect("failed to chmod a stub");
        };
        write_stub("cmake", cmake);
        write_stub("ninja", ninja);

        let script = dir.path().join("build.sh");
        fs_err::write(&script, render_with(BuildPlatform::Unix, extra_args))
            .expect("failed to write the script");

        let output = Command::new("bash")
            .arg(&script)
            .current_dir(dir.path())
            .env("ARGV_RECORD", &record)
            .env("PATH", format!("{}:/usr/bin:/bin", dir.path().display()))
            .env("PREFIX", prefix)
            .env("CMAKE_ARGS", "")
            .env(
                "PYTHON",
                python.map_or_else(
                    || {
                        dir.path()
                            .join("no-such-python")
                            .to_string_lossy()
                            .into_owned()
                    },
                    str::to_string,
                ),
            )
            .output()
            .expect("failed to run the script");

        let recorded = fs_err::read_to_string(&record).unwrap_or_default();
        let invocations = recorded
            .split("--- invocation\n")
            .map(|invocation| {
                invocation
                    .lines()
                    .map(str::to_string)
                    .collect::<Vec<String>>()
            })
            .collect();

        (output, invocations)
    }

    /// The arguments of every configure call, which are the invocations that
    /// name a source directory. The discovery run comes first, the real
    /// configure after it.
    #[cfg(unix)]
    fn configure_invocations(prefix: &str, python: Option<&str>) -> Vec<Vec<String>> {
        let (output, invocations) =
            run_script(CMAKE_NINJA, NINJA_WITH_INSTALL, vec![], prefix, python);
        assert!(
            output.status.success(),
            "the script failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );

        invocations
            .into_iter()
            .filter(|arguments| arguments.iter().any(|argument| argument == "-S"))
            .collect()
    }

    /// The arguments of the real configure run for a manifest that declares
    /// `extra_args`.
    #[cfg(unix)]
    fn configure_arguments_with(extra_args: Vec<String>, prefix: &str) -> Vec<String> {
        let (output, invocations) =
            run_script(CMAKE_NINJA, NINJA_WITH_INSTALL, extra_args, prefix, None);
        assert!(
            output.status.success(),
            "the script failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );

        invocations
            .into_iter()
            .rfind(|arguments| arguments.iter().any(|argument| argument == "-S"))
            .expect("no configure invocation was recorded")
    }

    /// An argument holding a space is one argument. The shell has to be told
    /// that, rather than left to split on the whitespace.
    #[cfg(unix)]
    #[test]
    fn test_an_extra_argument_holding_a_space_arrives_whole() {
        let arguments = configure_arguments_with(
            vec![String::from("-DDESCRIPTION=a demo library")],
            "/tmp/prefix",
        );

        assert!(
            arguments.contains(&"-DDESCRIPTION=a demo library".to_string()),
            "the argument was split up: {arguments:?}"
        );
    }

    /// Configures a throwaway project with `extra_args` through the rendered
    /// script, using a real cmake, and returns what it recorded for `key`.
    ///
    /// The stub above sees the arguments the way the shell split them. Only
    /// cmake itself sees them the way cmake parses them, which on Windows is
    /// not the way cmd.exe parses the arguments of a batch file, so a quote
    /// can only be settled by asking cmake.
    fn cache_value_for(extra_args: Vec<String>, key: &str) -> Option<String> {
        // Ask cmake where it lives, rather than a shell, as the shells the two
        // platforms offer have nothing in common. ninja is its neighbour.
        let answer = tempfile::tempdir().expect("failed to create a temp dir");
        let found = answer.path().join("cmake-path");
        let finder = answer.path().join("find.cmake");
        fs_err::write(
            &finder,
            format!(
                "file(WRITE \"{}\" \"${{CMAKE_COMMAND}}\")\n",
                found.to_string_lossy().replace('\\', "/")
            ),
        )
        .expect("failed to write the finder");

        let resolved = Command::new("pixi")
            .args(["exec", "--spec", "cmake", "--spec", "ninja", "--", "cmake"])
            .arg("-P")
            .arg(&finder)
            .output()
            .expect("failed to resolve cmake through pixi");
        assert!(
            resolved.status.success(),
            "pixi could not provide cmake: {}",
            String::from_utf8_lossy(&resolved.stderr)
        );

        let cmake = fs_err::read_to_string(&found).expect("cmake reported no path");
        let bin = Path::new(cmake.trim())
            .parent()
            .expect("cmake sits in a directory")
            .to_path_buf();

        let source = tempfile::tempdir().expect("failed to create a temp dir");
        fs_err::write(
            source.path().join("CMakeLists.txt"),
            "cmake_minimum_required(VERSION 3.20)\nproject(demo NONE)\ninstall(CODE \"message(STATUS ok)\")\n",
        )
        .expect("failed to write the project");

        let workdir = tempfile::tempdir().expect("failed to create a temp dir");
        let work = workdir.path().join("work");
        fs_err::create_dir_all(&work).expect("failed to create the work directory");

        let build_platform = if cfg!(windows) {
            BuildPlatform::Windows
        } else {
            BuildPlatform::Unix
        };
        let rendered = context(
            build_platform,
            &source.path().to_string_lossy(),
            extra_args,
            &[],
        )
        .render();

        let script = work.join(if cfg!(windows) {
            "build.bat"
        } else {
            "build.sh"
        });
        fs_err::write(&script, rendered).expect("failed to write the script");

        let mut command = if cfg!(windows) {
            let mut command = Command::new("cmd");
            command.arg("/c").arg(&script);
            command
        } else {
            let mut command = Command::new("bash");
            command.arg(&script);
            command
        };

        let output = command
            .current_dir(&work)
            .env(
                "PATH",
                std::env::join_paths(std::iter::once(bin).chain(std::env::split_paths(
                    &std::env::var_os("PATH").unwrap_or_default(),
                )))
                .expect("failed to build a PATH"),
            )
            .env("PREFIX", workdir.path().join("prefix"))
            .env("LIBRARY_PREFIX", workdir.path().join("prefix"))
            .env("CMAKE_ARGS", "")
            .env("PYTHON", work.join("no-such-python"))
            .output()
            .expect("failed to run the build script");
        assert!(
            output.status.success(),
            "the build script failed: {}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );

        let cache = fs_err::read_to_string(work.join("build").join(crate::cmake_cache::CACHE_FILE))
            .expect("cmake wrote no cache");

        crate::cmake_cache::entry(&cache, key).map(ToString::to_string)
    }

    /// The same value, settled by cmake rather than by the shell. On unix the
    /// stub already proves the split; this proves the parse.
    #[test]
    fn test_a_quote_reaches_cmake_itself() {
        let value = cache_value_for(
            vec![String::from(r#"-DDEMO_TEXT=a "quoted" word"#)],
            "DEMO_TEXT",
        );

        assert_eq!(value.as_deref(), Some(r#"a "quoted" word"#));
    }

    /// cmd.exe hands the command line to cmake unsplit, and cmake parses it
    /// with the Windows rules, where a literal quote inside a quoted argument
    /// is written by doubling it. Nothing on another platform exercises that.
    #[cfg(windows)]
    #[test]
    fn test_a_quote_survives_cmd_exe() {
        let value = cache_value_for(
            vec![String::from(r#"-DDEMO_TEXT=a "quoted" word"#)],
            "DEMO_TEXT",
        );

        assert_eq!(value.as_deref(), Some(r#"a "quoted" word"#));
    }

    /// A value holding a space, settled the same way.
    #[cfg(windows)]
    #[test]
    fn test_a_space_survives_cmd_exe() {
        let value = cache_value_for(vec![String::from("-DDEMO_TEXT=two words")], "DEMO_TEXT");

        assert_eq!(value.as_deref(), Some("two words"));
    }

    /// A quote inside the value is part of the value, and has to reach cmake
    /// as one, without ending the quoting that holds the argument together.
    #[cfg(unix)]
    #[test]
    fn test_an_extra_argument_holding_a_quote_arrives_whole() {
        let arguments = configure_arguments_with(
            vec![String::from(r#"-DJSON={"unit": "a demo"}"#)],
            "/tmp/prefix",
        );

        assert!(
            arguments.contains(&r#"-DJSON={"unit": "a demo"}"#.to_string()),
            "the quotes did not survive: {arguments:?}"
        );
    }

    /// Quoting must not cost the expansion, which is most of why an argument
    /// is written by hand. The expanded value holds a space of its own here,
    /// which must not split it either.
    #[cfg(unix)]
    #[test]
    fn test_an_extra_argument_still_expands_a_variable() {
        let arguments = configure_arguments_with(
            vec![String::from("-DSCHEMA_DIR=$PREFIX/share")],
            "/tmp/a prefix with spaces",
        );

        assert!(
            arguments.contains(&"-DSCHEMA_DIR=/tmp/a prefix with spaces/share".to_string()),
            "the variable did not expand into one argument: {arguments:?}"
        );
    }

    /// The arguments of the real configure run, which follows the discovery.
    #[cfg(unix)]
    fn configure_arguments(prefix: &str, python: Option<&str>) -> Vec<String> {
        configure_invocations(prefix, python)
            .pop()
            .expect("no configure invocation was recorded")
    }

    #[cfg(unix)]
    #[test]
    fn test_configure_gets_a_spaced_prefix_as_one_argument() {
        let arguments = configure_arguments("/tmp/a prefix with spaces", None);

        assert!(
            arguments.contains(&"-DCMAKE_INSTALL_PREFIX=/tmp/a prefix with spaces".to_string()),
            "the prefix was split up: {arguments:?}"
        );
    }

    /// The interpreter flag must not go through CMAKE_ARGS, which the
    /// configure step expands unquoted and would split on the space.
    #[test]
    fn test_the_python_flag_bypasses_cmake_args() {
        for platform in [BuildPlatform::Unix, BuildPlatform::Windows] {
            let script = render(platform);
            assert!(
                !script.contains("CMAKE_ARGS% -DPython_EXECUTABLE")
                    && !script.contains("CMAKE_ARGS -DPython_EXECUTABLE"),
                "the interpreter is appended to CMAKE_ARGS on {platform}"
            );
            assert!(
                script.contains("PYTHON_ARG"),
                "the interpreter flag has no variable of its own on {platform}"
            );
        }
    }

    #[cfg(unix)]
    #[test]
    fn test_configure_gets_a_spaced_interpreter_as_one_argument() {
        use std::os::unix::fs::PermissionsExt;

        // The probe only passes the flag on for an executable file.
        let home = tempfile::tempdir().expect("failed to create a temp dir");
        let python = home.path().join("a dir with spaces").join("python");
        fs_err::create_dir_all(python.parent().unwrap()).unwrap();
        fs_err::write(&python, "#!/bin/sh\nexit 0\n").unwrap();
        let mut permissions = fs_err::metadata(&python).unwrap().permissions();
        permissions.set_mode(0o755);
        fs_err::set_permissions(&python, permissions).unwrap();

        let arguments = configure_arguments("/tmp/prefix", Some(&python.to_string_lossy()));

        assert!(
            arguments.contains(&format!("-DPython_EXECUTABLE={}", python.display())),
            "the interpreter path was split up: {arguments:?}"
        );
    }

    /// Without an interpreter the flag must vanish rather than arrive empty,
    /// which would make cmake complain about an unparsable definition.
    #[cfg(unix)]
    #[test]
    fn test_configure_gets_no_python_flag_without_an_interpreter() {
        let arguments = configure_arguments("/tmp/prefix", None);

        assert!(
            !arguments
                .iter()
                .any(|argument| argument.contains("Python_EXECUTABLE")),
            "an interpreter flag was passed anyway: {arguments:?}"
        );
        assert!(
            !arguments.iter().any(|argument| argument.is_empty()),
            "an empty argument reached cmake: {arguments:?}"
        );
    }

    /// CMake emits no install target for a project that installs nothing, and
    /// the build would fail on ninja's `unknown target install`. The script
    /// has to say what is actually wrong, and say it before building.
    #[cfg(unix)]
    #[test]
    fn test_a_project_that_installs_nothing_is_told_so() {
        let (output, invocations) = run_script(
            CMAKE_NINJA,
            NINJA_WITHOUT_INSTALL,
            vec![],
            "/tmp/prefix",
            None,
        );

        assert!(
            !output.status.success(),
            "the build was allowed to produce a package with no files"
        );

        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stderr.contains("install()"),
            "the message does not name what is missing: {stderr}"
        );

        assert!(
            !invocations
                .iter()
                .any(|arguments| arguments.iter().any(|argument| argument == "--build")),
            "the project was built before the missing install target was reported"
        );
    }

    /// A generator other than ninja, which extra-args can still ask for,
    /// leaves no build.ninja to query. The check has to stand aside there
    /// rather than fail a build that works.
    #[cfg(unix)]
    #[test]
    fn test_another_generator_is_left_alone() {
        let (output, _) = run_script(
            CMAKE_OTHER_GENERATOR,
            NINJA_WITHOUT_INSTALL,
            vec![],
            "/tmp/prefix",
            None,
        );

        assert!(
            output.status.success(),
            "the install check fired without a ninja build tree to query: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    /// The discovery run has to come first, in its own build tree, with the
    /// provider registered. The real configure must follow it without one.
    #[cfg(unix)]
    #[test]
    fn test_the_discovery_run_precedes_the_real_configure() {
        let invocations = configure_invocations("/tmp/prefix", None);

        assert_eq!(invocations.len(), 2, "expected a discovery and a real run");
        let [discovery, real] = &invocations[..] else {
            unreachable!("just asserted the length")
        };

        assert!(
            discovery
                .iter()
                .any(|argument| argument.starts_with("-DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=")),
            "the discovery run does not register the provider: {discovery:?}"
        );
        assert!(
            discovery
                .iter()
                .any(|argument| argument == discovery::DISCOVERY_DIR),
            "the discovery run shares the real build directory: {discovery:?}"
        );
        assert!(
            !real
                .iter()
                .any(|argument| argument.contains("CMAKE_PROJECT_TOP_LEVEL_INCLUDES")),
            "the real configure must not inherit the provider: {real:?}"
        );
        assert!(
            real.contains(&"-DCMAKE_BUILD_TYPE=Release".to_string()),
            "the real configure lost its arguments: {real:?}"
        );
    }

    /// The provider has to record what was asked for and whether it was found,
    /// and stand in for what is missing so one run sees every package.
    /// Discovery is for the first configure only; a rebuild must not pay for
    /// it again.
    #[test]
    fn test_the_discovery_run_is_skipped_once_the_build_tree_exists() {
        for platform in [BuildPlatform::Unix, BuildPlatform::Windows] {
            let script = render(platform);
            let discovery = script
                .find(discovery::DISCOVERY_DIR)
                .expect("a discovery run");
            let guard = script
                .find("build.ninja")
                .expect("a guard on the build tree");

            assert!(
                guard < discovery,
                "the discovery run is not guarded by the build tree on {platform}"
            );
        }
    }
}
