//! The dependency discovery run and what it reports.
//!
//! Before the real configure, the build script runs a throwaway one with a
//! CMake dependency provider registered. The provider is called ahead of every
//! `find_package()` search: it repeats the search CMake would have done,
//! records the outcome, and stands in for whatever is missing so that a single
//! run reports every package the project looks for.
//!
//! This module writes that provider and reads back what it recorded.

use std::{
    io,
    path::{Path, PathBuf},
};

use crate::inputs::cmake_build_dir;

/// Directory the discovery run builds in, a sibling of the real build tree.
const DISCOVERY_DIR: &str = "pixi-discovery";

/// Where the provider records what the project searched for.
const FIND_LOG: &str = "pixi-find-package.log";

/// A package the project searched for.
#[derive(Debug, PartialEq, Eq)]
pub struct SearchedPackage {
    pub name: String,
    /// The search was a `REQUIRED` one, so the build cannot go without it.
    pub required: bool,
    /// The search succeeded.
    pub found: bool,
}

impl SearchedPackage {
    /// How the package reads in a message to the user.
    fn describe(&self) -> String {
        let kind = if self.required {
            "required"
        } else {
            "optional"
        };
        format!("{} ({kind})", self.name)
    }
}

/// Renders the CMake file that registers the dependency provider.
///
/// `log_file` is the path the provider appends its findings to, as CMake will
/// see it.
pub fn provider_file_lines(log_file: &str) -> Vec<String> {
    let mut lines = vec![
        "# Generated by pixi-build-cmake for the dependency discovery run.".to_string(),
        format!(r#"set(PIXI_FIND_LOG "{log_file}" CACHE INTERNAL "")"#),
    ];

    lines.extend(
        [
            r#"file(WRITE "${PIXI_FIND_LOG}" "")"#,
            "macro(pixi_provide_dependency method package_name)",
            r#"set(_pixi_args "")"#,
            "set(_pixi_kind optional)",
            "foreach(_pixi_arg IN ITEMS ${ARGN})",
            r#"if(_pixi_arg STREQUAL "REQUIRED")"#,
            "set(_pixi_kind required)",
            "else()",
            r#"list(APPEND _pixi_args "${_pixi_arg}")"#,
            "endif()",
            "endforeach()",
            // BYPASS_PROVIDER runs the search CMake would have done, without
            // calling us again.
            "find_package(${package_name} ${_pixi_args} BYPASS_PROVIDER QUIET)",
            "if(${package_name}_FOUND)",
            r#"file(APPEND "${PIXI_FIND_LOG}" "found ${_pixi_kind} ${package_name}\n")"#,
            "else()",
            r#"file(APPEND "${PIXI_FIND_LOG}" "missing ${_pixi_kind} ${package_name}\n")"#,
            // Stand in for the missing package so the run reaches the rest.
            "if(NOT TARGET ${package_name}::${package_name})",
            "add_library(${package_name}::${package_name} INTERFACE IMPORTED GLOBAL)",
            "endif()",
            "set(${package_name}_FOUND TRUE)",
            "endif()",
            "endmacro()",
            "cmake_language(SET_DEPENDENCY_PROVIDER pixi_provide_dependency",
            "    SUPPORTED_METHODS FIND_PACKAGE)",
        ]
        .map(String::from),
    );

    lines
}

/// Where the discovery run leaves its record, given the work directory of a
/// build.
fn find_log(workdir: &Path) -> PathBuf {
    cmake_build_dir(workdir)
        .with_file_name(DISCOVERY_DIR)
        .join(FIND_LOG)
}

/// Returns every package the discovery run searched for, or an error when it
/// left no record, for instance because the build tree was already configured.
pub fn searched_packages(workdir: &Path) -> io::Result<Vec<SearchedPackage>> {
    let recorded = fs_err::read_to_string(find_log(workdir))?;
    Ok(recorded.lines().filter_map(parse_line).collect())
}

/// Parses one `<outcome> <kind> <name>` line, ignoring anything malformed.
fn parse_line(line: &str) -> Option<SearchedPackage> {
    let mut fields = line.split_whitespace();
    let outcome = fields.next()?;
    let kind = fields.next()?;
    let name = fields.next()?;

    Some(SearchedPackage {
        name: name.to_string(),
        required: kind == "required",
        found: match outcome {
            "found" => true,
            "missing" => false,
            _ => return None,
        },
    })
}

/// Tells the user which packages the project looked for and did not find.
///
/// A missing required package fails the build on its own, with CMake's error.
/// A missing optional one is quieter and more dangerous: the feature it guards
/// is simply left out of the package.
pub fn report_missing_packages(workdir: &Path) {
    let packages = match searched_packages(workdir) {
        Ok(packages) => packages,
        Err(err) => {
            tracing::debug!("no dependency discovery record for this build: {err}");
            return;
        }
    };

    let (found, missing): (Vec<_>, Vec<_>) = packages.iter().partition(|package| package.found);
    tracing::debug!(
        "the project searched for {} packages, {} of them were found",
        packages.len(),
        found.len()
    );

    if missing.is_empty() {
        return;
    }

    let names: Vec<String> = missing.iter().map(|package| package.describe()).collect();
    tracing::warn!(
        "the build looked for packages that the environment does not have: {}. \
         Add the ones the package needs to host-dependencies; the full record is in {}",
        names.join(", "),
        find_log(workdir).display()
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Writes a discovery record for a work directory.
    fn write_log(workdir: &Path, contents: &str) {
        let log = find_log(workdir);
        fs_err::create_dir_all(log.parent().expect("the log has a parent")).unwrap();
        fs_err::write(log, contents).unwrap();
    }

    #[test]
    fn test_reads_what_the_provider_recorded() {
        let workdir = tempfile::tempdir().unwrap();
        write_log(
            workdir.path(),
            "found required ZLIB\nmissing optional SomeThing\nmissing required MustHave\n",
        );

        let packages = searched_packages(workdir.path()).unwrap();

        assert_eq!(
            packages,
            vec![
                SearchedPackage {
                    name: "ZLIB".to_string(),
                    required: true,
                    found: true
                },
                SearchedPackage {
                    name: "SomeThing".to_string(),
                    required: false,
                    found: false
                },
                SearchedPackage {
                    name: "MustHave".to_string(),
                    required: true,
                    found: false
                },
            ]
        );
    }

    /// The record sits next to the build tree, not inside it, so the file API
    /// and ninja never see it.
    #[test]
    fn test_the_record_is_a_sibling_of_the_build_tree() {
        let workdir = Path::new("/work");

        assert_eq!(
            find_log(workdir),
            Path::new("/work/work/pixi-discovery/pixi-find-package.log")
        );
        assert_ne!(
            find_log(workdir).parent(),
            Some(cmake_build_dir(workdir).as_path())
        );
    }

    #[test]
    fn test_a_build_without_a_discovery_record() {
        let workdir = tempfile::tempdir().unwrap();

        assert!(searched_packages(workdir.path()).is_err());
        // Reporting has to stay quiet rather than fail the build.
        report_missing_packages(workdir.path());
    }

    #[test]
    fn test_malformed_lines_are_skipped() {
        let workdir = tempfile::tempdir().unwrap();
        write_log(
            workdir.path(),
            "found required ZLIB\n\ngarbage\nmissing\nunknown optional Thing\n",
        );

        let packages = searched_packages(workdir.path()).unwrap();

        assert_eq!(packages.len(), 1);
        assert_eq!(packages[0].name, "ZLIB");
    }

    #[test]
    fn test_how_a_package_reads_in_a_message() {
        let required = SearchedPackage {
            name: "MustHave".to_string(),
            required: true,
            found: false,
        };
        let optional = SearchedPackage {
            name: "NiceToHave".to_string(),
            required: false,
            found: false,
        };

        assert_eq!(required.describe(), "MustHave (required)");
        assert_eq!(optional.describe(), "NiceToHave (optional)");
    }

    #[test]
    fn test_the_provider_records_and_substitutes() {
        let lines = provider_file_lines("/build/pixi-find-package.log").join("\n");

        assert!(
            lines.contains("BYPASS_PROVIDER"),
            "the provider must run the search cmake would have done"
        );
        assert!(lines.contains("found ${_pixi_kind} ${package_name}"));
        assert!(lines.contains("missing ${_pixi_kind} ${package_name}"));
        assert!(
            lines.contains("set(_pixi_kind required)"),
            "required and optional requests are not told apart"
        );
        assert!(
            lines.contains("INTERFACE IMPORTED GLOBAL"),
            "a missing package is not stood in for, so the run stops at the first one"
        );
        assert!(lines.contains("/build/pixi-find-package.log"));
    }
}
