#![doc = "This file was automatically generated by the varlink rust generator"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use async_trait::async_trait;
use serde_derive::{Deserialize, Serialize};
use std::io::BufRead;
use std::sync::Arc;
use varlink::{self, CallTrait};
#[allow(dead_code)]
#[derive(Clone, PartialEq, Debug)]
#[allow(clippy::enum_variant_names)]
pub enum ErrorKind {
    Varlink_Error,
    VarlinkReply_Error,
    AuthenticationFailed(Option<AuthenticationFailed_Args>),
    GlobalInstallFailed(Option<GlobalInstallFailed_Args>),
    WorkspaceNotFound(Option<WorkspaceNotFound_Args>),
}
impl ::std::fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ErrorKind::Varlink_Error => write!(f, "Varlink Error"),
            ErrorKind::VarlinkReply_Error => write!(f, "Varlink error reply"),
            ErrorKind::AuthenticationFailed(v) => {
                write!(f, "dev.prefix.pixi.AuthenticationFailed: {:#?}", v)
            }
            ErrorKind::GlobalInstallFailed(v) => {
                write!(f, "dev.prefix.pixi.GlobalInstallFailed: {:#?}", v)
            }
            ErrorKind::WorkspaceNotFound(v) => {
                write!(f, "dev.prefix.pixi.WorkspaceNotFound: {:#?}", v)
            }
        }
    }
}
pub struct Error(
    pub ErrorKind,
    pub Option<Box<dyn std::error::Error + 'static + Send + Sync>>,
    pub Option<&'static str>,
);
impl Error {
    #[allow(dead_code)]
    pub fn kind(&self) -> &ErrorKind {
        &self.0
    }
}
impl From<ErrorKind> for Error {
    fn from(e: ErrorKind) -> Self {
        Error(e, None, None)
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.1
            .as_ref()
            .map(|e| e.as_ref() as &(dyn std::error::Error + 'static))
    }
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}
impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        use std::error::Error as StdError;
        if let Some(ref o) = self.2 {
            std::fmt::Display::fmt(o, f)?;
        }
        std::fmt::Debug::fmt(&self.0, f)?;
        if let Some(e) = self.source() {
            std::fmt::Display::fmt("\nCaused by:\n", f)?;
            std::fmt::Debug::fmt(&e, f)?;
        }
        Ok(())
    }
}
#[allow(dead_code)]
pub type Result<T> = std::result::Result<T, Error>;
impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        match e.kind() {
            varlink::ErrorKind::VarlinkErrorReply(r) => Error(
                ErrorKind::from(r),
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
            _ => Error(
                ErrorKind::Varlink_Error,
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
        }
    }
}
#[allow(dead_code)]
impl Error {
    pub fn source_varlink_kind(&self) -> Option<&varlink::ErrorKind> {
        use std::error::Error as StdError;
        let mut s: &dyn StdError = self;
        while let Some(c) = s.source() {
            let k = self
                .source()
                .and_then(|e| e.downcast_ref::<varlink::Error>())
                .map(|e| e.kind());
            if k.is_some() {
                return k;
            }
            s = c;
        }
        None
    }
}
impl From<&varlink::Reply> for ErrorKind {
    #[allow(unused_variables)]
    fn from(e: &varlink::Reply) -> Self {
        match e {
            varlink::Reply { error: Some(t), .. }
                if t == "dev.prefix.pixi.AuthenticationFailed" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::AuthenticationFailed(v),
                        Err(_) => ErrorKind::AuthenticationFailed(None),
                    },
                    _ => ErrorKind::AuthenticationFailed(None),
                }
            }
            varlink::Reply { error: Some(t), .. } if t == "dev.prefix.pixi.GlobalInstallFailed" => {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::GlobalInstallFailed(v),
                        Err(_) => ErrorKind::GlobalInstallFailed(None),
                    },
                    _ => ErrorKind::GlobalInstallFailed(None),
                }
            }
            varlink::Reply { error: Some(t), .. } if t == "dev.prefix.pixi.WorkspaceNotFound" => {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::WorkspaceNotFound(v),
                        Err(_) => ErrorKind::WorkspaceNotFound(None),
                    },
                    _ => ErrorKind::WorkspaceNotFound(None),
                }
            }
            _ => ErrorKind::VarlinkReply_Error,
        }
    }
}
#[allow(dead_code)]
pub trait VarlinkCallError: varlink::CallTrait {
    fn reply_authentication_failed(&mut self, r#challenge: String) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "dev.prefix.pixi.AuthenticationFailed",
            Some(
                serde_json::to_value(AuthenticationFailed_Args { r#challenge })
                    .map_err(varlink::map_context!())?,
            ),
        ))
    }
    fn reply_global_install_failed(&mut self, r#message: String) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "dev.prefix.pixi.GlobalInstallFailed",
            Some(
                serde_json::to_value(GlobalInstallFailed_Args { r#message })
                    .map_err(varlink::map_context!())?,
            ),
        ))
    }
    fn reply_workspace_not_found(&mut self, r#path: String) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "dev.prefix.pixi.WorkspaceNotFound",
            Some(
                serde_json::to_value(WorkspaceNotFound_Args { r#path })
                    .map_err(varlink::map_context!())?,
            ),
        ))
    }
}
impl VarlinkCallError for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#EnvironmentInfo {
    pub r#name: String,
    pub r#features: Vec<String>,
    pub r#solve_group: Option<String>,
    pub r#platforms: Vec<String>,
    pub r#dependencies: Vec<String>,
    pub r#pypi_dependencies: Vec<String>,
    pub r#tasks: Vec<String>,
    pub r#prefix: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#InstalledPackage {
    pub r#name: String,
    pub r#version: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#WorkspaceInfo {
    pub r#name: String,
    pub r#manifest_path: String,
    pub r#version: Option<String>,
    pub r#pixi_version: String,
    pub r#environments: Vec<EnvironmentInfo>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct AuthenticationFailed_Args {
    pub r#challenge: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct GlobalInstallFailed_Args {
    pub r#message: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct WorkspaceNotFound_Args {
    pub r#path: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct ConfirmGlobalInstall_Reply {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#sha: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#sha_dir: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#packages: Option<Vec<InstalledPackage>>,
}
impl varlink::VarlinkReply for ConfirmGlobalInstall_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct ConfirmGlobalInstall_Args {
    pub r#challenge: String,
}
#[allow(dead_code)]
pub trait Call_ConfirmGlobalInstall: VarlinkCallError + Send {
    fn reply(
        &mut self,
        r#message: Option<String>,
        r#sha: Option<String>,
        r#sha_dir: Option<String>,
        r#packages: Option<Vec<InstalledPackage>>,
    ) -> varlink::Result<()> {
        self.reply_struct(
            ConfirmGlobalInstall_Reply {
                r#message,
                r#sha,
                r#sha_dir,
                r#packages,
            }
            .into(),
        )
    }
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct GlobalInstall_Reply {
    pub r#challenge: String,
}
impl varlink::VarlinkReply for GlobalInstall_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct GlobalInstall_Args {
    pub r#packages: Vec<String>,
    pub r#channels: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#platform: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#environment: Option<String>,
    pub r#expose: Vec<String>,
    pub r#with: Vec<String>,
    pub r#force_reinstall: bool,
    pub r#no_shortcuts: bool,
    pub r#client_envs_dir: String,
}
#[allow(dead_code)]
pub trait Call_GlobalInstall: VarlinkCallError + Send {
    fn reply(&mut self, r#challenge: String) -> varlink::Result<()> {
        self.reply_struct(GlobalInstall_Reply { r#challenge }.into())
    }
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Info_Reply {
    pub r#workspace: WorkspaceInfo,
}
impl varlink::VarlinkReply for Info_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Info_Args {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#manifest_path: Option<String>,
}
#[allow(dead_code)]
pub trait Call_Info: VarlinkCallError + Send {
    fn reply(&mut self, r#workspace: WorkspaceInfo) -> varlink::Result<()> {
        self.reply_struct(Info_Reply { r#workspace }.into())
    }
}
#[allow(dead_code)]
#[derive(Default)]
pub struct AsyncCall {
    continues: bool,
    more: bool,
    oneway: bool,
    replies: Vec<varlink::Reply>,
}
impl AsyncCall {
    pub fn new(more: bool, oneway: bool) -> Self {
        AsyncCall {
            continues: false,
            more,
            oneway,
            replies: Vec::new(),
        }
    }
    pub fn take_replies(&mut self) -> Vec<varlink::Reply> {
        std::mem::take(&mut self.replies)
    }
}
impl varlink::CallTrait for AsyncCall {
    fn reply_struct(&mut self, mut reply: varlink::Reply) -> varlink::Result<()> {
        if self.continues {
            if !self.more {
                return Err(varlink::context!(varlink::ErrorKind::CallContinuesMismatch));
            }
            reply.continues = Some(true);
        }
        self.replies.push(reply);
        Ok(())
    }
    fn set_continues(&mut self, cont: bool) {
        self.continues = cont;
    }
    fn to_upgraded(&mut self) {}
    fn is_oneway(&self) -> bool {
        self.oneway
    }
    fn wants_more(&self) -> bool {
        self.more
    }
    fn get_request(&self) -> Option<&varlink::Request<'_>> {
        None
    }
}
impl VarlinkCallError for AsyncCall {}
impl Call_ConfirmGlobalInstall for AsyncCall {}
impl Call_GlobalInstall for AsyncCall {}
impl Call_Info for AsyncCall {}
#[async_trait]
#[allow(dead_code)]
pub trait VarlinkInterface {
    async fn confirm_global_install(
        &self,
        call: &mut dyn Call_ConfirmGlobalInstall,
        r#challenge: String,
    ) -> varlink::Result<()>;
    async fn global_install(
        &self,
        call: &mut dyn Call_GlobalInstall,
        r#packages: Vec<String>,
        r#channels: Vec<String>,
        r#platform: Option<String>,
        r#environment: Option<String>,
        r#expose: Vec<String>,
        r#with: Vec<String>,
        r#force_reinstall: bool,
        r#no_shortcuts: bool,
        r#client_envs_dir: String,
    ) -> varlink::Result<()>;
    async fn info(
        &self,
        call: &mut dyn Call_Info,
        r#manifest_path: Option<String>,
    ) -> varlink::Result<()>;
    fn call_upgraded(
        &self,
        _call: &mut varlink::Call,
        _bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        Ok(Vec::new())
    }
}
#[allow(dead_code)]
pub trait VarlinkClientInterface {
    fn confirm_global_install(
        &self,
        r#challenge: String,
    ) -> varlink::AsyncMethodCall<ConfirmGlobalInstall_Args, ConfirmGlobalInstall_Reply, Error>;
    fn global_install(
        &self,
        r#packages: Vec<String>,
        r#channels: Vec<String>,
        r#platform: Option<String>,
        r#environment: Option<String>,
        r#expose: Vec<String>,
        r#with: Vec<String>,
        r#force_reinstall: bool,
        r#no_shortcuts: bool,
        r#client_envs_dir: String,
    ) -> varlink::AsyncMethodCall<GlobalInstall_Args, GlobalInstall_Reply, Error>;
    fn info(
        &self,
        r#manifest_path: Option<String>,
    ) -> varlink::AsyncMethodCall<Info_Args, Info_Reply, Error>;
}
#[allow(dead_code)]
pub struct VarlinkClient {
    connection: Arc<varlink::AsyncConnection>,
}
impl VarlinkClient {
    #[allow(dead_code)]
    pub fn new(connection: Arc<varlink::AsyncConnection>) -> Self {
        VarlinkClient { connection }
    }
}
impl VarlinkClientInterface for VarlinkClient {
    fn confirm_global_install(
        &self,
        r#challenge: String,
    ) -> varlink::AsyncMethodCall<ConfirmGlobalInstall_Args, ConfirmGlobalInstall_Reply, Error>
    {
        varlink :: AsyncMethodCall :: < ConfirmGlobalInstall_Args , ConfirmGlobalInstall_Reply , Error > :: new (self . connection . clone () , "dev.prefix.pixi.ConfirmGlobalInstall" , ConfirmGlobalInstall_Args { r#challenge })
    }
    fn global_install(
        &self,
        r#packages: Vec<String>,
        r#channels: Vec<String>,
        r#platform: Option<String>,
        r#environment: Option<String>,
        r#expose: Vec<String>,
        r#with: Vec<String>,
        r#force_reinstall: bool,
        r#no_shortcuts: bool,
        r#client_envs_dir: String,
    ) -> varlink::AsyncMethodCall<GlobalInstall_Args, GlobalInstall_Reply, Error> {
        varlink::AsyncMethodCall::<GlobalInstall_Args, GlobalInstall_Reply, Error>::new(
            self.connection.clone(),
            "dev.prefix.pixi.GlobalInstall",
            GlobalInstall_Args {
                r#packages,
                r#channels,
                r#platform,
                r#environment,
                r#expose,
                r#with,
                r#force_reinstall,
                r#no_shortcuts,
                r#client_envs_dir,
            },
        )
    }
    fn info(
        &self,
        r#manifest_path: Option<String>,
    ) -> varlink::AsyncMethodCall<Info_Args, Info_Reply, Error> {
        varlink::AsyncMethodCall::<Info_Args, Info_Reply, Error>::new(
            self.connection.clone(),
            "dev.prefix.pixi.Info",
            Info_Args { r#manifest_path },
        )
    }
}
#[allow(dead_code)]
pub struct VarlinkInterfaceHandler {
    inner: Arc<dyn VarlinkInterface + Send + Sync>,
}
#[allow(dead_code)]
pub fn new(inner: Arc<dyn VarlinkInterface + Send + Sync>) -> VarlinkInterfaceHandler {
    VarlinkInterfaceHandler { inner }
}
#[async_trait]
impl varlink::AsyncConnectionHandler for VarlinkInterfaceHandler {
    async fn handle(
        &self,
        server: &mut varlink::sansio::Server,
        _upgraded_iface: Option<String>,
    ) -> varlink::Result<Option<String>> {
        while let Some(event) = server.poll_event() {
            match event {
                varlink::sansio::ServerEvent::Request { request } => {
                    let more = request.more.unwrap_or(false);
                    let oneway = request.oneway.unwrap_or(false);
                    let mut call = AsyncCall::new(more, oneway);
                    match request.method.as_ref() {
                        "dev.prefix.pixi.ConfirmGlobalInstall" => {
                            if let Some(args) = request.parameters {
                                let args: ConfirmGlobalInstall_Args = serde_json::from_value(args)
                                    .map_err(|e| {
                                        varlink::Error(
                                            varlink::ErrorKind::InvalidParameter(e.to_string()),
                                            None,
                                            None,
                                        )
                                    })?;
                                self.inner
                                    .confirm_global_install(
                                        &mut call as &mut dyn Call_ConfirmGlobalInstall,
                                        args.r#challenge,
                                    )
                                    .await?;
                            } else {
                                call.reply_invalid_parameter("parameters".into())?;
                            }
                        }
                        "dev.prefix.pixi.GlobalInstall" => {
                            if let Some(args) = request.parameters {
                                let args: GlobalInstall_Args = serde_json::from_value(args)
                                    .map_err(|e| {
                                        varlink::Error(
                                            varlink::ErrorKind::InvalidParameter(e.to_string()),
                                            None,
                                            None,
                                        )
                                    })?;
                                self.inner
                                    .global_install(
                                        &mut call as &mut dyn Call_GlobalInstall,
                                        args.r#packages,
                                        args.r#channels,
                                        args.r#platform,
                                        args.r#environment,
                                        args.r#expose,
                                        args.r#with,
                                        args.r#force_reinstall,
                                        args.r#no_shortcuts,
                                        args.r#client_envs_dir,
                                    )
                                    .await?;
                            } else {
                                call.reply_invalid_parameter("parameters".into())?;
                            }
                        }
                        "dev.prefix.pixi.Info" => {
                            if let Some(args) = request.parameters {
                                let args: Info_Args =
                                    serde_json::from_value(args).map_err(|e| {
                                        varlink::Error(
                                            varlink::ErrorKind::InvalidParameter(e.to_string()),
                                            None,
                                            None,
                                        )
                                    })?;
                                self.inner
                                    .info(&mut call as &mut dyn Call_Info, args.r#manifest_path)
                                    .await?;
                            } else {
                                call.reply_invalid_parameter("parameters".into())?;
                            }
                        }
                        method => {
                            call.reply_method_not_found(method.to_string())?;
                        }
                    }
                    for reply in call.take_replies() {
                        server.send_reply(reply)?;
                    }
                }
                varlink::sansio::ServerEvent::Upgrade { interface } => {
                    return Ok(Some(interface));
                }
            }
        }
        Ok(None)
    }
}
impl varlink::AsyncInterface for VarlinkInterfaceHandler {
    fn get_name(&self) -> &'static str {
        "dev.prefix.pixi"
    }
    fn get_description(&self) -> &'static str {
        "# Pixi workspace management over varlink IPC\ninterface dev.prefix.pixi\n\ntype EnvironmentInfo (\n    name: string,\n    features: []string,\n    solve_group: ?string,\n    platforms: []string,\n    dependencies: []string,\n    pypi_dependencies: []string,\n    tasks: []string,\n    prefix: string\n)\n\ntype WorkspaceInfo (\n    name: string,\n    manifest_path: string,\n    version: ?string,\n    pixi_version: string,\n    environments: []EnvironmentInfo\n)\n\n# A package that was installed.\ntype InstalledPackage (\n    name: string,\n    version: string\n)\n\nmethod Info(manifest_path: ?string) -> (workspace: WorkspaceInfo)\n\n# Install packages globally. Returns a challenge UUID. The client must create\n# .pixi-server-auth-<challenge> in client_envs_dir, then call ConfirmGlobalInstall.\nmethod GlobalInstall(\n    packages: []string,\n    channels: []string,\n    platform: ?string,\n    environment: ?string,\n    expose: []string,\n    with: []string,\n    force_reinstall: bool,\n    no_shortcuts: bool,\n    client_envs_dir: string\n) -> (challenge: string)\n\n# Confirm that the auth file was created. The server checks for the file,\n# installs the environment, and returns the result.\n# With \"more\", the server streams progress as intermediate replies with only\n# the \"message\" field set, followed by a final reply with the full result.\nmethod ConfirmGlobalInstall(challenge: string) -> (\n    message: ?string,\n    sha: ?string,\n    sha_dir: ?string,\n    packages: ?[]InstalledPackage\n)\n\nerror WorkspaceNotFound(path: string)\nerror GlobalInstallFailed(message: string)\nerror AuthenticationFailed(challenge: string)\n"
    }
}
